// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjrmcieesdgfevzoksaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqcm1jaWVlc2RnZmV2em9rc2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMTY5MzcsImV4cCI6MjA2NzY5MjkzN30.JJhB6neKO6w0ESICVfPeeqH1JqVbZkN37UypoZzxFvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});